### ISSUE TITLE
Little visual issues and little bugs

### ISSUE THREAD

**Issue by PromethTK11** [mattroks101/Interstation-Two#1]
- [ ] "Grid techfloor tile" does not have a sprite https://cdn.discordapp.com/attachments/262719888932601866/264101378459172865/unknown.png
 
- [ ]  Little bug with the last item of a toolbelt, it floats in the HuD https://cdn.discordapp.com/attachments/262719888932601866/264102579334545408/unknown.png

- [ ] Looks like in some areas all lights that you turn on there does not update when the character or the source of light moves inside the character (Maybe it's that there aren't areas in that part of the map?) https://gyazo.com/c2be85f6e95c50f6c2ded81339ee5e3d.gif

I'll update this when i find more

**Comment by mattroks101** [comment]
Fixed.
